### ISSUE TITLE
Account password visible in cmd history / process tree

### ISSUE THREAD

**Issue by scitor** [llbit/minechat#2]
The application requires the account password to be typed in clear text in the command line, which will be saved in the command history and visible to any user logged in for the entire time the process is running.

Please provide a possibility to pass the password in a secure manner, like an environment variable, interactive prompt or a config file.

The following workaround may be used as long as this issue exists:
http://serverfault.com/questions/592744/how-to-hide-a-password-passed-as-command-line-argument

**Comment by llbit** [comment]
I didn't add an interactive password prompt using e.g. readline because my use cases only included starting the chat client via a script.

Feel free to make a pull request with an interactive password prompt in case the user didn't pass a password on the command line.
